<?php
require_once("../../../configuration/connection_inc.php");
require_once("../../../function/email.php");
require_once("../../../function/menu.php");
require_once("get_sql.php");

$lebar = "style='width:120px;cellpadding:2px;color:#ffffff'";
$lebar2 = "style='width:350px;cellpadding:2px;color:#ffffff'";

$header = "<table style='border: solid 1px #cccccc;border-padding:5px;font-size:12;font-type:arial'>
             <tR style='background-color:#000F9F;border: solid 1px #ccc'>
		     <td align='center' $lebar>PRODUCT ID</td>
			 <td align='center'  $lebar2>PRODUCT NAME</td>
			 <td align='center' $lebar>CURRENCY</td>
			 <td align='center'  $lebar>SO ( * )</td>
			 <td align='center' $lebar>DO</td>
			 <td align='center' $lebar>DO vs SO %</td>";
		
		$tgl_awal = substr(date('Y-m-d',strtotime(date('m/d/Y'))),0,8).'01';
		$tgl_akhir = date('Y-m-d',strtotime(date('m/d/Y')));
		
	
		$tgl_awal_lastyear = date('Y-m-d',strtotime('-1 year',strtotime($tgl_awal)));
		$tgl_akhir_lastyear = date('Y-m-d',strtotime('-1 year',strtotime($tgl_akhir)));
		
	    $so = 0;
		$do = 0;
		$netsales =0;
		$pembagi = 1;
		$sql = "select distinct a.product_id,d.product_name,b.c_symbol, a.quantity*a.sale_price as total 
				from sales_order_item a,sales_order b, distributor c, product d 
				where a.quotation_id=b.quotation_id and b.distributor_id=c.distributor_id 
				and c.distributor_group='export' and a.product_id=d.product_id and
				CONVERT(VARCHAR(10), b.quotation_date, 120) between '$tgl_awal' and '$tgl_akhir'";
				
		$qx = odbc_exec($conn2,$sql);
		while($rx = odbc_fetch_array($qx)){
			$product = "select product_name from product where product_id='$rx[product_id]'";
			$qproduct = odbc_exec($conn2,$product);
			$rproduct = odbc_fetch_array($qproduct);
			@$sodo = do_product_export($tgl_awal,$tgl_akhir,$rx[product_id])/$rx[total]*100;
			
			@$so = $so + $rx[total]/$pembagi;
			@$do = $do + do_product_export($tgl_awal,$tgl_akhir,$rx[product_id])/$pembagi;
			
			$isi = $isi."<tr>
	    			<td>$rx[product_id]</td>
					<td>$rx[product_name]</td>
					<td align='center'>$rx[c_symbol]</td>
     			    <td align='right'>".number_format($rx[total]/$pembagi,2,',','.')."</td>
					<td align='right'>".number_format(do_product_export($tgl_awal,$tgl_akhir,$rx[product_id])/$pembagi,2,',','.')."</td>
					<td align='right'>".number_format($sodo,2,',','.')." %</td>
				  </tr><tr><td colspan=8></td></tr>"; 
		}
		@$total_sodo = $do / $so * 100;

		$footer = "<tr style='font-weight:bold'>
				<td colspan=3 align='center'>TOTAL</td>
				<td align='right'>".number_format($so,2,',','.')."</td>
				<td align='right'>".number_format($do,2,',','.')."</td>
				<td align='right'>".number_format($total_sodo,2,',','.')." %</td>
			 </tr></table>";
		
		$body = $header.$isi.$footer;


//kirim email ke penerima
$user = mysql_query("select a.*,b.full_name,b.email,c.report_name,c.keterangan from email_notification a,sec_users b,master_report c 
                     where a.user_id=b.user_id and a.report_id=17 and a.report_id=c.report_id");
while($r = mysql_fetch_array($user)){						    
	if($rows == '')
		$rows .=$r[email];
	else
		$rows .=','.$r[email];
	
	$keterangan = $r[keterangan];
	$subject = $r[report_name];
	$fullname = $r[full_name];
	$keterangan = $r[keterangan];
}	

$awal = "Dear All. ".ucwords($full_name)."<br><br>$keterangan - ".date('M Y')."<Br><Br>";
$akhir = "<br><i>Gross Value = Quantity * Price list</i>
		  <br><br>This report generated by system<br>Date Generate : ".date('d M Y H:m:s')." WIB<br>";
$from = $rows; 
$headers = "From: no-reply\r\n";
$headers .= "Reply-to: ".$from."\r\n";
$headers .= "MIME-Version: 1.0\r\n";
$headers .= "Content-Type: text/html; charset=UTF-8\r\n"; 
$message = $awal.$body.$akhir;

//kirim email 
$mail_sent = @mail($from, $subject, $message, $headers);	
		
?>